version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - mongodb-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db   # Persistenza dei dati del database

networks:
  mongodb-network:

volumes:
  mongodb_data:   # Definizione del volume per la persistenza dei dati

